baetyl-455
baetyl/baetyl-cloud pull request #69
Opened 2020-08-24 08:02 UTC by xumengdi01

2020-08-24 09:33 UTC, ludanfeng requested changes

2020-08-24 09:33 UTC, ludanfeng commented on api/node.go
> +	nameArray := strings.Split(names, ",")
批量接口，都是body提供资源列表的，不要放在url里，更不要定义逗号这种分隔符

2020-08-24 11:16 UTC, allen-lj commented on api/node.go
> +	nameArray := strings.Split(names, ",")
可以在body里定义一个数组

2020-08-25 03:20 UTC, ludanfeng requested changes

2020-08-25 03:20 UTC, ludanfeng commented on server/router.go
> +		nodes.POST("/batch", common.Wrapper(s.api.GetNodes))
url没出现冲突？按照规范不应该是:PUT /v1/nodes?batch
另外规范提到："为控制HTTP请求的大小，批量操作的对象数量应有上限，通常不超过1000。单条记录特别大时该数量还应该进一步减少。"
我们控制100个

2020-08-25 03:50 UTC, xumengdi01 commented on server/router.go
> +		nodes.POST("/batch", common.Wrapper(s.api.GetNodes))
POST /v1/nodes/batch不会冲突

试了下 PUT /v1/nodes?batch 和 POST /v1/nodes?batch
这两个url会冲突

2020-08-26 08:52 UTC, allen-lj commented on server/router.go
> +		nodes.PUT("", common.Wrapper(s.api.GetNodes))
url为空？

2020-08-26 09:03 UTC, allen-lj commented on api/node.go
> +		if err != nil {
这个err需要分类型处理，not found可以忽略，其他情况不能忽略err

2020-08-26 09:05 UTC, allen-lj commented on api/node.go
> +			continue
同上，err不能忽略

2020-08-26 09:22 UTC, xumengdi01 commented on server/router.go
> +		nodes.PUT("", common.Wrapper(s.api.GetNodes))
/v1/nodes?batch    查询参数不会被算入路由

2020-08-27 06:13 UTC, allen-lj commented on api/node.go
> +			if e, ok := err.(errors.Coder); ok && e.Code() == common.ErrResourceNotFound {
这个err里没有not found

2020-08-27 06:39 UTC, allen-lj commented on common/validate.go
> +		panic(fe.(error).Error())
尽量不要使用panic

2020-08-27 06:44 UTC, allen-lj commented on common/validate.go
> +func translate(trans ut.Translator, fe validator.FieldError) string {
不用translate函数

2020-08-27 06:44 UTC, allen-lj commented on common/validate.go
> +func registerTranslator(tag string, msg string) validator.RegisterTranslationsFunc {
这个也不需要

2020-08-27 07:28 UTC, allen-lj commented on api/node.go
> +			if e, ok := err.(errors.Coder); ok && e.Code() == common.ErrResourceNotFound {
直接retrun err

2020-08-27 07:31 UTC, allen-lj commented on models/node.go
> +	Names []string `json:"names,"validate:"validBatchOp"`
maxLength=20

2020-08-27 08:56 UTC, allen-lj approved these changes

2020-08-28 04:12 UTC, ludanfeng approved these changes

2020-08-28 04:13 UTC, merged