active server重构
baetyl/baetyl-cloud pull request #81
Opened 2020-08-31 08:36 UTC by yibishufange

2020-08-31 14:49 UTC, allen-lj commented on service/active.go
> +	InfoKind      = "k"
Info是否类似shortname？

2020-08-31 14:51 UTC, allen-lj commented on api/active.go
> +	service.ActiveService
这个作为成员变量，不适合内联

2020-08-31 14:56 UTC, allen-lj commented on service/active.go
> +func (api *ActiveServiceImpl) CheckAndParseToken(token string) (map[string]interface{}, error) {
check是否可以能放到api层

2020-08-31 15:43 UTC, ludanfeng requested changes

2020-08-31 15:43 UTC, ludanfeng commented on api/node.go
> +func (api *API) genCmd(kind, ns, name string) (string, error) {
先移到template service上吧，通过cache service从 property 表里获取active的地址

2020-08-31 15:43 UTC, ludanfeng commented on service/active.go
> +		res, err := api.InitService.GetResource(common.ResourceMetrics)
InitService移除，交给template service 读取模板文件和模板替换后返回
sysConfigService也会废弃，不要再用

2020-09-01 10:09 UTC, ludanfeng requested changes

2020-09-01 10:09 UTC, ludanfeng commented on service/node.go
> +	GetDesireAppInfo(ns, nodeName string) (*specV1.Application, error)
GetDesire ？
放回specV1.Desire，在用它的函数去获取app信息

2020-09-01 10:09 UTC, ludanfeng commented on service/node.go
> +	for _, appInfo := range apps {
这个逻辑太tricky了，不应该是node的逻辑

2020-09-01 10:09 UTC, ludanfeng commented on service/template.go
> +	CmdExpirationInSeconds = int64(60 * 60)
？

2020-09-01 10:09 UTC, ludanfeng commented on service/template.go
> +	auth  AuthService
?

2020-09-01 15:23 UTC, ludanfeng requested changes

2020-09-01 15:23 UTC, ludanfeng commented on api/init_test.go
> +func initActiveAPI(t *testing.T) (*InitAPIImpl, *gin.Engine, *gomock.Controller) {
active都替换一下

2020-09-01 15:23 UTC, ludanfeng commented on scripts/demo/native/templates/baetyl-init.yml
> +---
文件名改一下：baetyl-init-deployment.yml
内容后面再整理吧，可以找赵鑫协助，移除所有激活的配置

2020-09-01 15:23 UTC, ludanfeng commented on scripts/sql/data.sql
> +("baetyl-init", "baetyltechtest/baetyl:git-84127d1");
baetyl-init -> baetyl-image
后面我还会加上 baetyl-function-image

2020-09-01 15:23 UTC, ludanfeng commented on server/init_server.go
>  // NewActiveServer new active server
全局搜索active替换

2020-09-01 15:23 UTC, ludanfeng commented on service/init.go
> +		cfg:			config,
执行一下make fmt

2020-09-01 15:23 UTC, ludanfeng commented on service/init.go
> +func (a *InitServiceImpl) CheckAndParseToken(token string) (map[string]interface{}, error) {
auth不应该放在service层，api层做完校验再调用service层的业务逻辑

2020-09-01 15:23 UTC, ludanfeng commented on service/node.go
> +	GetDesire(ns, nodeName string) (*specV1.Desire, error)
跟上面命名保持一致：namespace, name string

2020-09-01 15:23 UTC, ludanfeng commented on service/node.go
> +			common.Field("type", "node"),
common.Field("type", "shadow"),

2020-09-02 02:57 UTC, ludanfeng approved these changes

2020-09-02 03:03 UTC, merged